- name: Get log files
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ kyoushi_gather_logs_dir }}"
    mode: pull
    copy_links: yes
    delete: yes
    recursive: yes
    use_ssh_args: yes
    times: yes
    perms: no
    rsync_opts: "{{ kyoushi_gather_rsync_extra_options + (item.exclude | default([]) | map('regex_replace', '(.*)', '--exclude=\\1') | list) }}"
  become: yes
  ignore_errors: "{{ kyoushi_gather_ignore_errors }}"
  loop: "{{ __kyoushi_gather_logs }}"

- name: Get config files
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ kyoushi_gather_configs_dir }}/"
    mode: pull
    copy_links: yes
    delete: yes
    recursive: yes
    use_ssh_args: yes
    times: yes
    perms: no
    rsync_opts: "{{ kyoushi_gather_rsync_extra_options + (item.exclude | default([]) | map('regex_replace', '(.*)', '--exclude=\\1') | list) }}"
  become: yes
  ignore_errors: "{{ kyoushi_gather_ignore_errors }}"
  loop: "{{ __kyoushi_gather_configs }}"
